#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7BFB1108D92765AF (stefw@gnome.org)
#
Name     : adcli
Version  : 0.8.2
Release  : 3
URL      : https://www.freedesktop.org/software/realmd/releases/adcli-0.8.2.tar.gz
Source0  : https://www.freedesktop.org/software/realmd/releases/adcli-0.8.2.tar.gz
Source99 : https://www.freedesktop.org/software/realmd/releases/adcli-0.8.2.tar.gz.sig
Summary  : Active Directory account management tool
Group    : Development/Tools
License  : LGPL-2.1
Requires: adcli-bin = %{version}-%{release}
Requires: adcli-license = %{version}-%{release}
Requires: adcli-man = %{version}-%{release}
BuildRequires : cyrus-sasl-dev
BuildRequires : docbook-xml
BuildRequires : e2fsprogs-dev
BuildRequires : krb5-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : openldap-dev
BuildRequires : util-linux
BuildRequires : xmlto

%description
adcli
A helper library and tools for Active Directory client operations.

%package bin
Summary: bin components for the adcli package.
Group: Binaries
Requires: adcli-license = %{version}-%{release}

%description bin
bin components for the adcli package.


%package doc
Summary: doc components for the adcli package.
Group: Documentation
Requires: adcli-man = %{version}-%{release}

%description doc
doc components for the adcli package.


%package license
Summary: license components for the adcli package.
Group: Default

%description license
license components for the adcli package.


%package man
Summary: man components for the adcli package.
Group: Default

%description man
man components for the adcli package.


%prep
%setup -q -n adcli-0.8.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557076163
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557076163
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/adcli
cp COPYING %{buildroot}/usr/share/package-licenses/adcli/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/adcli

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/adcli/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/adcli/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/adcli.8
